<?php require __DIR__ . '/include/header.phtml';?>

<div class="container">
	<?php foreach($products->fetchAll() as $product): ?>
	<div class="col-md-4">
		<img src="http://placehold.it/350x150" alt="">
		<h2>
			<a href="<?=HOME;?>/produto/<?=$product['slug'];?>"><?=utf8_encode($product['name']);?></a>
		</h2>
		<p>R$ <?=number_format($product['price'], 2, ',', '.');?></p>
	</div>
	<?php endforeach; ?>
</div>
<?php require __DIR__ . '/include/footer.phtml';?>
