<?php require __DIR__ . '/include/header.phtml';?>
<div class="container">
	<div class="col-md-12">
		<div class="col-md-6">
			<img src="http://placehold.it/350x150" alt="">
		</div>
		<div class="col-md-6">
			<h2>
			<a href=""><?=utf8_encode($product['name']);?></a>
		</h2>
		<p><?=$product['description'];?></p>
		<p>R$ <?=number_format($product['price'], 2, ',', '.');?></p>
		</div>
	</div>
</div>
<?php require __DIR__ . '/include/footer.phtml';?>
